#!/usr/bin/env node
// Writes docs/theme-store-listing.md (BUILD_SPEC §8.4) from scripts/src/theme-listing.mjs, after
// checking the listing rules: tagline and highlight lengths, industries, catalog sizes, feature
// names, features Weft doesn't offer, and the Theme Store text rules.
//
//   node scripts/build-listing.mjs            write the file
//   node scripts/build-listing.mjs --check    exit 1 when the file is out of date or a rule fails
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import listing, { rules, featureSources, reviewNotes } from './src/theme-listing.mjs';
import catalogs from './src/demo-catalog.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(ROOT, 'docs/theme-store-listing.md');
const check = process.argv.includes('--check');
const presets = JSON.parse(readFileSync(join(ROOT, 'config/settings_data.json'), 'utf8').replace(/^\s*\/\*[\s\S]*?\*\//, '')).presets;
const COMPANY = {
  weft: ['Boutique Luna S.L.', 'Lucía Márquez', 'Madrid Serrano, Valencia Ruzafa'],
  tress: ['Salón Onda S.L.', 'Marta Ruiz', 'Barcelona Gràcia, Girona Centre'],
  balm: ['Casa Alma Concept Store S.L.', 'Elena Vidal', 'Seville Triana, Málaga Centro']
};

export function listingProblems() {
  const problems = [];
  const allFeatures = new Set(Object.values(rules.features).flat());
  const TEXT = [
    [/\b(best|ultimate|world-class|perfect|revolutionary|#1|number one)\b/i, 'no marketing hyperbole'],
    [/shopify/i, 'no Shopify name in listing highlights'],
    [/\b(colours?|catalogues?|centre|customis\w*|organis\w*|favourite)\b/i, 'American English']
  ];
  for (const [key, l] of Object.entries(listing)) {
    const at = `listing ${key}`;
    if (!presets[l.name]) problems.push(`${at}: preset "${l.name}" is not in config/settings_data.json`);
    if (l.tagline.length > rules.taglineMax) problems.push(`${at}: tagline is ${l.tagline.length} characters (max ${rules.taglineMax})`);
    if (!rules.industries.includes(l.industry)) problems.push(`${at}: industry "${l.industry}" is not a Theme Store industry`);
    if (!rules.catalogSizes.includes(l.catalogSize)) problems.push(`${at}: catalog size "${l.catalogSize}" is not a Theme Store option`);
    const products = catalogs[key].products.length;
    if (l.catalogSize === 'Some (11-100+)' && products < 11) problems.push(`${at}: the demo catalog has ${products} products, fewer than the catalog size tag`);
    if (l.highlights.length !== 3) problems.push(`${at}: needs exactly three key highlights`);
    for (const h of l.highlights) {
      if (h.title.length > rules.highlightTitleMax) problems.push(`${at}: highlight "${h.title}" title is ${h.title.length} characters (max ${rules.highlightTitleMax})`);
      if (h.text.length > rules.highlightTextMax) problems.push(`${at}: highlight "${h.title}" text is ${h.text.length} characters (max ${rules.highlightTextMax})`);
    }
    for (const f of l.features) {
      if (!allFeatures.has(f)) problems.push(`${at}: "${f}" is not a Theme Store feature name`);
      if (rules.notOffered.includes(f)) problems.push(`${at}: "${f}" is not offered by the theme`);
      if (!featureSources[f]) problems.push(`${at}: "${f}" has no source in the theme listed`);
    }
    if (new Set(l.features).size !== l.features.length) problems.push(`${at}: duplicate features`);
    const texts = [l.tagline, l.metaDescription, ...l.highlights.flatMap((h) => [h.title, h.text])];
    for (const t of texts) for (const [re, why] of TEXT) if (re.test(t)) problems.push(`${at}: "${t.slice(0, 50)}": ${why}`);
  }
  return problems;
}

const table = (head, rows) => [
  `| ${head.join(' | ')} |`,
  `|${head.map(() => '---').join('|')}|`,
  ...rows.map((r) => `| ${r.map((c) => String(c ?? '').replace(/\|/g, '\\|')).join(' | ')} |`)
].join('\n');

function render() {
  const out = ['# Theme Store listing', ''];
  out.push(`Listing text for the Partner Dashboard (BUILD_SPEC §8.4). Generated by \`scripts/build-listing.mjs\` from \`scripts/src/theme-listing.mjs\`, which checks it against the listing rules on [shopify.dev](${rules.source}) (read ${rules.read}). Edit the source, not this file.`, '');
  out.push('Fields marked **Owner** need the owner\'s accounts or decisions and are listed under "Owner actions" in `docs/progress.md`.', '');

  out.push('## Theme', '');
  out.push(table(['Field', 'Value'], [
    ['Theme name', 'Weft (from `config/settings_schema.json`; can\'t change after the first upload)'],
    ['Presets', `${Object.values(listing).map((l) => l.name).join(', ')} (from \`config/settings_data.json\`; names can't change after the first upload)`],
    ['ZIP', '`node scripts/package-theme.mjs --themestore`, then `shopify theme package` (CI builds both on every push)'],
    ['Price', '**Owner** (the form takes $100 to $500 in steps of $10)'],
    ['Documentation link', '**Owner**: publish `docs/documentation/` and enter its URL'],
    ['Support contact form', '**Owner**: a contact form URL (an email address alone isn\'t accepted)'],
    ['Review notification email', '**Owner**'],
    ['Theme submission contact email', '**Owner**; allow `theme-submissions@shopify.com` and `noreply@shopify.com`'],
    ['Google Analytics 4, remarketing, Meta pixel', 'Optional, **Owner**'],
    ['Merchant stores using the theme', 'Optional, up to five, screenshots 779 x 1000px; none until stores launch']
  ]), '');

  for (const [key, l] of Object.entries(listing)) {
    const [company, buyer, locations] = COMPANY[key];
    out.push(`## ${l.name} preset`, '');
    out.push(table(['Field', 'Value'], [
      ['Tagline', `${l.tagline} (${l.tagline.length} of ${rules.taglineMax})`],
      ['Primary industry', l.industry],
      ['Catalog size', `${l.catalogSize} (demo store: ${catalogs[key].products.length} products)`],
      ['Metadata description', l.metaDescription],
      ['Demo store URL', `**Owner**: the "${catalogs[key].store}" store (\`demo-content/${key}/\`)`]
    ]), '');
    out.push('### Key highlights', '', `Static images at ${rules.highlightImage}.`, '');
    out.push(table(['Title', 'Description', 'Image to capture'], l.highlights.map((h) => [
      `${h.title} (${h.title.length}/${rules.highlightTitleMax})`, `${h.text} (${h.text.length}/${rules.highlightTextMax})`, h.image
    ])), '');
    out.push('### Theme features', '');
    for (const [group, names] of Object.entries(rules.features)) {
      const picked = names.filter((n) => l.features.includes(n));
      if (picked.length) out.push(`- **${group}:** ${picked.join(', ')}`);
    }
    out.push('');
    out.push('### Screenshots', '', `Desktop home page at ${rules.desktop[1]} (or ${rules.desktop[0]}), mobile home page at ${rules.mobile}; no browser window, background or added text, and the mobile shot isn't a copy of the desktop one. \`node scripts/capture-screenshots.mjs --preset ${key} --url https://<demo store>\` takes both at the exact sizes.`, '');
    out.push(table(['Shot', 'Size', 'Alt text'], [
      ['Desktop home page', rules.desktop[1], l.screenshots.desktop],
      ['Mobile home page', rules.mobile, l.screenshots.mobile]
    ]), '');
    out.push('### Testing instructions', '');
    out.push('All demo stores use the same password: **Owner** (enter it here before submitting).', '');
    l.testing.forEach((t, i) => out.push(`${i + 1}. ${t}`));
    out.push('', `**Wholesale test contact:** company ${company}, contact ${buyer}, locations ${locations}. Customer accounts sign in with a one-time code sent by email, so to see wholesale mode add your own email as a contact of ${company} with the Ordering only role on both locations (Customers > Companies in the demo store admin), then sign in from the account icon with that email. **Owner**: or enter here the contact email the review team should use.`, '');
  }

  out.push('## Theme review notes', '', reviewNotes, '');
  out.push('## Feature sources', '', 'Where each selected feature lives in the theme, for answering review questions.', '');
  const used = [...new Set(Object.values(listing).flatMap((l) => l.features))];
  out.push(table(['Feature', 'In the theme'], used.map((f) => [f, featureSources[f]])), '');
  out.push('## Submission checklist (BUILD_SPEC §8.4)', '');
  out.push(table(['Step', 'State'], [
    ['1. Read the current rules', `Done ${rules.read}: requirements, listings, submission (shopify.dev)`],
    ['2. One demo store per preset', '**Owner**: follow `demo-content/<preset>/README.md`'],
    ['3. Screenshots', '**Owner**: `scripts/capture-screenshots.mjs` on each demo store'],
    ['4. Listing per preset', 'Text above; **Owner**: documentation URL, contact form, emails, price'],
    ['5. Submit', '**Owner**: upload the CI zip in Partner Dashboard > Themes > Submit a theme'],
    ['6. Review feedback', 'Fix every listed issue before resubmitting']
  ]), '');
  return out.join('\n');
}

const problems = listingProblems();
const body = render();
if (check) {
  if (!existsSync(FILE) || readFileSync(FILE, 'utf8') !== body) problems.push('docs/theme-store-listing.md is out of date (run node scripts/build-listing.mjs)');
} else {
  writeFileSync(FILE, body);
}
for (const p of problems) console.log(`WARNING ${p}`);
console.log(`build-listing: ${Object.keys(listing).length} preset listings${check ? ' checked' : ' written'}, ${problems.length} problems`);
process.exit(problems.length ? 1 : 0);
